export const products = [
    {
        id: 1,
        name:"REMERA SPRT ESTAMPADA",
        price:9999,
        descriptionTitle:"UNA REMERA PARA USO DIARIO INSPIRADA EN LOS ARCHIVOS DE ADIDAS",
        description: "El legado de adidas abarca géneros, generaciones y mucho más allá de lo esperado. No tiene límites. Llevá esta mentalidad contigo cada vez que te ponés esta remera. Bueno, irradiálo siempre, pero si en algún momento te hace falta los logos adidas te ayudarán a recordar su importancia. Sin importar el lugar tendrás siempre la sensación suave del algodón en tu piel. Nuestros productos de algodón apoyan el cultivo de algodón sostenible. Esto hace parte de nuestro anhelo de ponerle fin a la contaminación por plástico.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a4b8f1bbe93f402d852cac3701229210_9366/Remera_SPRT_Estampada_Negro_GN2441_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 2,
        name:"REMERA MUST HAVES ESTAMPADA",
        price:7499,
        descriptionTitle:"UNA REMERA LLAMATIVA QUE DESTACA TU AMOR POR EL DEPORTE",
        description: "¿Solo ves flores? Acercate un poco más. Las ramas llevan a pelotas de básquet y fútbol, y los colores vivos te ayudan a mantener alto tu nivel de energía para enfrentarte a los meses más fríos del año. Mientras soñás con días soleados en la cancha, ponete esta llamativa remera adidas y contagiáte de la emoción que sentís con cada partido.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d6f338d8bd334311985bac1700fef1d3_9366/Remera_Must_Haves_Estampada_Granate_FR7138_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 3,
        name:"REMERA CAMUFLAJE",
        price:10999,
        descriptionTitle:"REMERA CON ESTAMPADO MODERNO DEL TRIFOLIO EN CAMUFLAJE",
        description: "Oculta a plena vista. Una versión moderna de un patrón clásico, esta camiseta luce un logo del Trifolio en camuflaje. Creá un look contemporáneo con la energía del legado adidas.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/dc243360329a43d6915baacb00de0fe9_9366/Remera_Camuflaje_Negro_FM3338_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 4,
        name:"REMERA ADICOLOR CLASSICS 3 TIRAS",
        price:10999,
        descriptionTitle:"UNA REMERA AJUSTADA DE ALGODÓN CON LAS ICÓNICAS 3 TIRAS",
        description: "No hay que complicar las cosas. Lucí un look adidas auténtico cuando llevás puesta esta remera. Los detalles en contraste convierten esta remera sencilla en algo único. Su tejido es tan suave que seguramente no te la vas a querer quitar.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2b7c10c6bc05442d93c2ac84007241f4_9366/Remera_Adicolor_Classics_3_Tiras_Negro_GN3495_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 5,
        name:"REMERA BRUSHSTROKE LOGO BOX ESTAMPADA",
        price:4599,
        descriptionTitle:"UNA REMERA CLÁSICA DE CUELLO REDONDO",
        description: "Esta remera para uso diario es tan suave que te vas a enamorar de ella de inmediato. Tiene un corte clásico y una energía deportiva que la hacen muy fácil de combinar con tus demás prendas y luce un distintivo estampado de adidas que le confiere un toque divertido y mucha personalidad.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/74d00042b62141d79c4fac82015886d7_9366/Remera_Brushstroke_Logo_Box_Estampada_Azul_GL2876_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 6,
        name:"REMERA 3 FRANJAS TAPE",
        price:5999,
        descriptionTitle:"UNA REMERA DE INSPIRACIÓN DEPORTIVA PARA CUALQUIER OCASIÓN",
        description: "Esta remera adidas con las clásicas 3 Franjas se adapta a cualquier atuendo deportivo. Añadí versatilidad a tu vestuario con un estilo que habla por sí mismo. Mostrar confianza es cosa nuestra, pero una ayuda externa nunca viene mal.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/522079c178fa42998155ab8000cb5ab9_9366/Remera_3_Franjas_Tape_Azul_FS4306_01_laydown.jpg",
        idCategory:1,
    },
    {
        id: 7,
        name:"PANTALÓN DEPORTIVO ADICOLOR CLASSICS PRIMEBLUE SST",
        price:25999,
        descriptionTitle:"UNA DE LAS DOS PIEZAS DEL CLÁSICO CONJUNTO CON TODA LA COMODIDAD",
        description: "Según los rumores, adidas introdujo el primer conjunto en 1964. No lo podemos confirmar, pero no cabe duda de que las 3 Tiras han pasado décadas sobresaliendo en las canchas, los estadios, las calles y muchos lugares más. No importa dónde estés, nunca pasan de moda. Este pantalón es una prueba clara de esto. Diseñado con la comodidad en mente, su tejido suave está hecho con hilo Parley Ocean Plastic reciclado a partir de desechos plásticos.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1c2febd0cacc4d6aa958ab8a00ff0a30_9366/Pantalon_Deportivo_Adicolor_Classics_Primeblue_SST_Negro_GF0210_01_laydown.jpg",
        idCategory:2,
    },
    {
        id: 8,
        name:"PANTALÓN DEPORTIVO MONOGRAMA ESTAMPADO",
        price:28999,
        descriptionTitle:"UN PANTALÓN DEPORTIVO CLÁSICO CON UN DISEÑO LLAMATIVO",
        description: "No siempre podés gritarlo. Pero sí podés mostrar tu amor por adidas de cintura a tobillo con el enérgico estampado de logos que adorna este pantalón deportivo. De esa manera, está claro en qué equipo estás. Liviano y cómodo, te permite hacer de todo con total comodidad.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/975312dee66a45e7a57aad1900cfa55b_9366/Pantalon_Deportivo_Monograma_Estampado_Negro_H13484_21_model.jpg",
        idCategory:2,
    },
    {
        id: 9,
        name:"PANTALÓN TRIFOLIO ADICOLOR ESSENTIALS",
        price:18999,
        descriptionTitle:"UN PANTALÓN ESTILIZADO Y CÓMODO PARA USAR A LO LARGO DEL DÍA",
        description: "Los pantalones perfectos cumplen tres criterios esenciales: Comodidad. Estilo. Facilidad de uso. Este par de adidas tiene un diseño minimalista y tejido polar grueso para mantenerte cómodo mientras te movés o te relajás.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4e3ed4e2a7864f00b78fad1a00ae5c9f_9366/Pantalon_Trifolio_Adicolor_Essentials_Gris_H34659_21_model.jpg",
        idCategory:2,
    },
    {
        id: 10,
        name:"ROMPEVIENTOS PRIMEGREEN ESSENTIALS 3 TIRAS",
        price:24999,
        descriptionTitle:"ROMPEVIENTOS CLÁSICO QUE TE HACE OLVIDAR LA PRESENCIA DEL VIENTO EN TUS ACTIVIDADES DIARIAS",
        description: "¿El viento no te deja disfrutar del parque? ¿Hace difícil tus salidas matutinas a correr? Tranquilo. Este rompevientos adidas liviano se encarga de ambos gracias a su tejido Primegreen resistente al viento que forma parte del compromiso de adidas para acabar con los residuos plásticos. El forro interno de malla y el cierre frontal mantienen tu cuerpo fresco y seco.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c0476b9cf5f5457b9b0faca8009b807f_9366/Rompevientos_Primegreen_Essentials_3_Tiras_Negro_GK9026_01_laydown.jpg",
        idCategory:3,
    },
    {
        id: 11,
        name:"ROMPEVIENTOS ESSENTIALS BRANDLOVE WOVEN",
        price:24999,
        descriptionTitle:"UN ROMPEVIENTOS ESTAMPADO HECHO CON MATERIALES RECICLADOS",
        description: "Este rompevientos adidas es perfecto para todo tipo de clima. Contemplá su extravagante marca en la parte frontal. Además de su diseño estilizado que está listo para la brisa. El dobladillo ajustable y la capucha te permiten moverte con total libertad.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c93d19bdaf7d48ddb271adc5015c1bae_9366/Rompevientos_Essentials_Brandlove_Woven_Negro_HE1773_21_model.jpg",
        idCategory:3,
    },
    {
        id: 12,
        name:"GORRA TREFOIL BASEBALL",
        price:7499,
        descriptionTitle:"EL AUTÉNTICO ESTILO DEL TRÉBOL",
        description: "Esta gorra de béisbol con visera curvada te permite lucir el mejor estilo. Se ha confeccionado con paneles de algodón y presenta un gran trébol bordado en el centro. Incluye un cierre regulable en la nuca para que puedas ajustarla a tu gusto.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9382df3f01f54fbf9a14a9610123ec22_9366/Gorra_Trefoil_Baseball_(UNISEX)_Negro_EC3603_01_standard.jpg",
        idCategory:4,
    },
    {
        id: 13,
        name:"GORRA DAILY",
        price:1999,
        descriptionTitle:"UN DISEÑO DEPORTIVO CON EL SELLO DE ADIDAS",
        description: "Protégete del sol con el estilo de adidas. Esta gorra con cierre ajustable en la nuca se ha confeccionado en sarga de algodón que le confiere un toque informal y moderno.",
        image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a1e374b1d9994b29b614ab73014a63fe_9366/Gorra_Daily_(UNISEX)_Gris_GE1165_01_standard.jpg",
        idCategory:4,
    },

    
    
]